# Generated by Django 4.1.7 on 2023-03-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='text_box',
            field=models.TextField(default='empty text', verbose_name='Ваши жалобы'),
            preserve_default=False,
        ),
    ]
