# Generated by Django 4.1.7 on 2023-03-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_testmodel_text_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='text_box',
            field=models.TextField(blank=True, null=True, verbose_name='Ваши жалобы'),
        ),
    ]
